name: 'Append to Gist'
inputs:
  gistURL: 
    description: 'URL to the gist'
    required: true
  token:
    description: 'Token able to append to the gist'
    required: true
  file:
    description: 'The filename containing the gist'
    required: true
  suffix:
    description: 'A suffix to append to a file'
    required: false
runs:
  using: 'node16'
  main: 'gist.js'
branding:
  icon: 'align-center'
  color: 'orange'
description: 'Appends the contents of file to a gist.'
